version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://fileshare:fileshare@db:5432/fileshare
      - SECRET_KEY=${SECRET_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - PYTHONPATH=/app
    volumes:
      - ./uploads:/app/uploads
      - ./migrations:/app/migrations
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fileshare
      - POSTGRES_USER=fileshare
      - POSTGRES_PASSWORD=fileshare

volumes:
  postgres_data:
